name: Daily Feishu Data Sync

on:
  schedule:
    # 每天北京时间早上 9 点运行 (UTC时间 1:00)
    # 你可以修改 cron 表达式来调整时间
    - cron: '28 4 * * *'
  workflow_dispatch: # 允许你在网页上有一个按钮手动点击运行测试

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        # 升级 pip 避免安装报错
        python -m pip install --upgrade pip
        # 安装必要的库，包括处理旧版 Excel 的 xlrd
        pip install pandas requests xlrd playwright
        # 安装浏览器驱动
        playwright install chromium
        # 【关键修复】安装系统级依赖库 (解决 Host system is missing dependencies 报错)
        playwright install-deps

    - name: Run Script
      env:
        # 这里把我们在 Settings 里配置的密码注入到环境变量中
        FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
        FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        DATA_TABLE_ID: ${{ secrets.DATA_TABLE_ID }}
        LOG_TABLE_ID: ${{ secrets.LOG_TABLE_ID }}
        WEB_USER: ${{ secrets.WEB_USER }}
        WEB_PASS: ${{ secrets.WEB_PASS }}
      run: python main.py
